# Generated by Django 5.2.6 on 2025-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='http://localhost:8000/token/')),
                ('default_expiration_hours', models.IntegerField(default=24)),
                ('default_error_correction', models.CharField(choices=[('L', '7%'), ('M', '15%'), ('Q', '25%'), ('H', '30%')], default='M', max_length=1)),
            ],
        ),
    ]
