# Generated by Django 5.2.6 on 2025-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('priority', models.IntegerField(default=0)),
                ('qr_expiration_hours', models.IntegerField(default=24)),
            ],
        ),
    ]
