# Generated by Django 5.2.6 on 2025-09-12 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('checksum', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('format', models.CharField(default='PNG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='SUCCESS', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='QRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='http://localhost:3000/token-status/')),
                ('default_size', models.IntegerField(default=10)),
                ('default_border', models.IntegerField(default=4)),
                ('error_correction', models.CharField(choices=[('L', 'L (7%)'), ('M', 'M (15%)'), ('Q', 'Q (25%)'), ('H', 'H (30%)')], default='M', max_length=1)),
                ('default_expiry_hours', models.IntegerField(default=24)),
                ('default_format', models.CharField(default='PNG', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('queue_position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
