# Generated by Django 5.2.6 on 2025-09-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='qr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='tokens.qrcode'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AddField(
            model_name='token',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tokens.token'),
        ),
    ]
