# Generated by Django 5.2.6 on 2025-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_qrtemplate_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('VALID', 'VALID'), ('EXPIRED', 'EXPIRED'), ('INVALID', 'INVALID')], default='VALID', max_length=20),
        ),
    ]
