# Generated by Django 5.2.6 on 2025-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_qrcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
