# Generated by Django 5.2.6 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_alter_token_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
