# Generated by Django 5.2.6 on 2025-09-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_qrcode_data'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='format',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='status',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.CharField(default='UNKNOWN', max_length=128),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='tokens.token'),
        ),
    ]
