# Generated by Django 5.2.6 on 2025-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_remove_qrcode_checksum_remove_qrcode_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='checksum',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
