# Generated by Django 5.2.6 on 2025-09-16 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0009_qrcode_checksum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='format',
            field=models.CharField(default='PNG', max_length=10),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
