# Generated by Django 5.2.6 on 2025-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_qrcode_created_by_qrcode_format_qrcode_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='source',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
