# Generated by Django 5.2.6 on 2025-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0012_token_created_by_alter_token_issued_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrsettings',
            old_name='default_border',
            new_name='border',
        ),
        migrations.RenameField(
            model_name='qrsettings',
            old_name='default_expiry_hours',
            new_name='expiry_hours',
        ),
        migrations.RemoveField(
            model_name='qrsettings',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='qrsettings',
            name='default_format',
        ),
        migrations.RemoveField(
            model_name='qrsettings',
            name='default_size',
        ),
        migrations.RemoveField(
            model_name='qrsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='qrsettings',
            name='size',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='qrsettings',
            name='error_correction',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
