# Generated by Django 5.2.6 on 2025-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0013_rename_default_border_qrsettings_border_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsettings',
            name='daily_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrsettings',
            name='generation_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='qrsettings',
            name='generation_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
