# Generated by Django 5.2.6 on 2025-09-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0014_qrsettings_daily_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscan',
            name='qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='tokens.qrcode'),
        ),
    ]
