# Generated by Django 5.2.6 on 2025-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0015_alter_qrscan_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='scan_count',
            field=models.IntegerField(default=1),
        ),
    ]
